### ISSUE TITLE
Gravel Miner Causing "net.minecraft.client.multiplayer.ClientPacketListener.m_6198_()"

### ISSUE THREAD

**Issue by Zelioth** [TwelveIterations/GravelMiner#14]
### Minecraft Version

1.19.x

### Mod Loader

Forge

### Mod Loader Version

43.1.3

### Mod Version

GravelMiner-Forge-1.19-13.0.0.jar

### Describe the Issue

I have been through every mod in my mod pack "Friends United" which is published on curse forge as a 1.19.2 mod pack. After going through every single mod and finding the singular issue causing the very first error in my launchers startup. Gravel miner is for some reason causing an issue. 

[14:35:08] [Thread-0/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.client.multiplayer.ClientPacketListener.m_6198_()" because the return value of "net.minecraft.client.Minecraft.m_91403_()" is null
	Index: 1

### Logs

https://pastebin.com/A2jLnN89

### Do you use any performance-enhancing mods (e.g. OptiFine)?

enabling this mod causes it, removing it fixes it.

**Comment by MagnusHJensen** [comment]
This is simply due to the fact, that the `ConfigReloadedEvent` is fired before a valid play connection is made. (Assuming on game load) and this mod banking on the fact, the connection is available.

Not sure where the responsibility lies, if it's in ForgeBalmNetworking, where it should gate messages from being sent if the connection is not available, or if each mod is responsible for ensuring the connection is valid before sending any messages.

_Edit: I'm gonna go ahead and make a PR for this mod to check the connection status, if @blay09 Wants the check in Balm, I can add it there instead_

**Comment by MagnusHJensen** [comment]
_Double Edit: It looks like it only fires this exception if loaded alongside other mods, if ran standalone no exceptions is fired, since the used mods requires forge 1.19.2, and this mod is at 1.19 I did not go ahead and create the PR, since that is a bigger change that I want to right now_

**Comment by Zelioth** [comment]
Good Morning, 

I just wanted to update this issue incase it ever became an issue to cause problems. I am working on my 1.19.3 pack update slowly and working on errors as I go. I think the issue that we are seeing is caused by balm not G.M. I could be very wrong but I did the same tests. Loaded the small pack with Gravel Miner, and without and with caused the same Multiplayer Exception error. I again don't know what issue this might cause but just want to make sure it's noticed and reported. 

[Without Gravel Debug.log](https://github.com/TwelveIterationMods/GravelMiner/files/10253260/Without.Gravel.Debug.log)
[With Gravel Debug.log](https://github.com/TwelveIterationMods/GravelMiner/files/10253261/With.Gravel.Debug.log)

**Comment by Zelioth** [comment]
Also I just read your responses again and understand a little better what you mean. That being said the issue does still exsist in 1.19.3 Forge version 44.0.30. Thank you for making this mod and I'll be including it in our pack again "Friends United" once the 1.19.3 pack is finished. I appreciate your work and update :D

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm version
