### ISSUE TITLE
GravelMiner triggers when breaking gravel blocks

### ISSUE THREAD

**Issue by Zero9o1o** [TwelveIterations/GravelMiner#2]
It might be nice for a option so you have to hold a button to allow the gravel miner to work cause i was trying to gather flint and i like to make pillars and gravel miner keep triggering

**Comment by BlayTheNinth** [comment]
GravelMiner is meant to only trigger when you break a non-gravel block I think.

**Comment by Zero9o1o** [comment]
Also you might want to make it check to see if the block below is air cause it will place the torches on the wall
