### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Knito58** [TwelveIterations/GravelMiner#8]
MC 1.12
Forge 14.21.1.2402
GravelMiner 6.1.1
SSP (Survival Single Player)

Config = default
No difference in mining with or without GravelMiner. Have 25 torches in hotbar (slot 8, last slot to the right). 

![config](https://www.dropbox.com/s/e4yu52oyot3xm65/gravelminerconfig.jpg?dl=1)

**Comment by BlayTheNinth** [comment]
Works just fine for me, what are you trying to do? You need to break the block *below* the gravel.

**Comment by Knito58** [comment]
... and when the block below is gravel, too? I just installed it and was eager to find some gravel. Now there it is. Looks as if I've hit the gravel in the middle. Breaking the bottom gravel block makes the rest fall as without the mod.
![Gravel veine](https://www.dropbox.com/s/f18qen0osv4l3r5/gravelfound.jpg?dl=1)

**Comment by Knito58** [comment]
Already broke some bottom gravel blocks - nothing new.

**Comment by Knito58** [comment]
Oh yeah it worked finally - but the block to destroy must not be gravel. Then it won't work.

**Comment by BlayTheNinth** [comment]
Yes, that's how it's supposed to work. The mod is meant to catch the gravel that would otherwise fall in your way when mining a tunnel through stone.

**Comment by Knito58** [comment]
Ok this seems to be the case mostly. I just had a bad starting.... So when I arrive at a gravel spot I need to dig down to find a non-gravel-block? However - this is nice. Will keep it.
:)
Thanks.

**Comment by BlayTheNinth** [comment]
#9

**Comment by Knito58** [comment]
Gravelminer 6.1.2

Yay! It works even when I hit a gravel vein in the middle. No more digging down to find the non-gravel-block. Now this is the "NAWAG" mod:  Never Again Worry About Gravel

Thank you!
